import numpy as np

print("****   Question :- 1 : Calculate the total revenue generated by two product categories in a store. ********")
category1_revenue = np.array([500, 600, 700, 550])
category2_revenue = np.array([450, 700, 800, 600])
total_revenue = category1_revenue + category2_revenue
print("Total Revenue:", total_revenue)

print("****   Question :- 2 : Calculate the profit made by a company.   ********")
revenue = np.array([10000, 12000, 11000, 10500])
expenses = np.array([4000, 5000, 4500, 4800])
profit = revenue - expenses
print("Profit : ", profit)

print("****   Question :- 3 : Determine which products in a store are out of stock (quantity is 0).   ********")

inventory = np.array([10, 0, 5, 0, 20, 0])
out_of_stock = np.where(inventory == 0)[0]
print("Out of Stock Products:", out_of_stock)

print("****   Question :- 4 : Calculate the total cost of items in a shopping cart, considering the quantity and price per item.     ********")

quantity = np.array([2, 3, 4, 1])
price_per_item = np.array([10.0, 5.0, 8.0, 12.0])
total_cost_per_item = quantity * price_per_item
total_cost = np.sum(total_cost_per_item)
print("TOtal cost per item : ",total_cost_per_item)
print("Total Cost: ", total_cost)

